x509userproxy           = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/proxy.cert
getenv                  = True
executable              = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/run_BTagCSV_C.sh
arguments               = $(args)
output = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/BTagCSV_C_C_20250602-220256/job_BTagCSV_C.$(ClusterId).$(ProcId).out
MY.WantOS               = "el9"
MY.XRDCP_CREATE_DIR     = True
error = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/BTagCSV_C_C_20250602-220256/error_BTagCSV_C.$(ClusterId).$(ProcId).err
log = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/BTagCSV_C_C_20250602-220256/log_BTagCSV_C.$(ClusterId).log
request_memory          = 10 GB
+JobFlavour             = "tomorrow"
queue args from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/ResubmittedJobV3/BTagCSV_C_C_20250602-220256/arguments_failed_BTagCSV_C_C_20250602-220256.txt
