description: Configuration for HADD-merged samples
samples:
  BTagCSV_B:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/BTagCSV_B.root
    label: Data
    color: '#000000'
  BTagCSV_C:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/BTagCSV_C.root
    label: Data
    color: '#000000'
  BTagCSV_D:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/BTagCSV_D.root
    label: Data
    color: '#000000'
  BTagCSV_E:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/BTagCSV_E.root
    label: Data
    color: '#000000'
  BTagCSV_F:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/BTagCSV_F.root
    label: Data
    color: '#000000'
  JetHT_B:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/JetHT_B.root
    label: Data
    color: '#000000'
  JetHT_C:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/JetHT_C.root
    label: Data
    color: '#000000'
  JetHT_D:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/JetHT_D.root
    label: Data
    color: '#000000'
  JetHT_E:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/JetHT_E.root
    label: Data
    color: '#000000'
  JetHT_F:
    type: DATA
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/JetHT_F.root
    label: Data
    color: '#000000'
  QCD_HT1000to1500:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT1000to1500.root
    label: QCD_HT1000to1500
    color: '#332288'
  QCD_HT1500to2000:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT1500to2000.root
    label: QCD_HT1500to2000
    color: '#88CCEE'
  QCD_HT2000toInf:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT2000toInf.root
    label: QCD_HT2000toInf
    color: '#44AA99'
  QCD_HT200to300:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT200to300.root
    label: QCD_HT200to300
    color: '#117733'
  QCD_HT300to500:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT300to500.root
    label: QCD_HT300to500
    color: '#999933'
  QCD_HT500to700:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT500to700.root
    label: QCD_HT500to700
    color: '#DDCC77'
  QCD_HT700to1000:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/QCD_HT700to1000.root
    label: QCD_HT700to1000
    color: '#CC6677'
  TTbar_DiLep:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbar_DiLep.root
    label: TTbar_DiLep
    color: '#882255'
  TTbar_Hadronic:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbar_Hadronic.root
    label: TTbar_Hadronic
    color: '#AA4499'
  TTbar_SemiLep:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbar_SemiLep.root
    label: TTbar_SemiLep
    color: '#DDDDDD'
  tt4b:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/tt4b.root
    label: tt4b
    color: '#332288'
  ttHH:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/ttHH.root
    label: ttHH
    color: '#88CCEE'
  ttHTobb:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/ttHTobb.root
    label: ttHTobb
    color: '#44AA99'
  TTWH:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTWH.root
    label: TTWH
    color: '#117733'
  TTWW:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTWW.root
    label: TTWW
    color: '#999933'
  TTWZ:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTWZ.root
    label: TTWZ
    color: '#DDCC77'
  TTZHTo4b:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTZHTo4b.root
    label: TTZHTo4b
    color: '#CC6677'
  TTZZTo4b:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTZZTo4b.root
    label: TTZZTo4b
    color: '#882255'
  TTZToBB:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTZToBB.root
    label: TTZToBB
    color: '#AA4499'
  TTbb_DiLep:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbb_DiLep.root
    label: TTbb_DiLep
    color: '#DDDDDD'
  TTbb_Hadronic:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbb_Hadronic.root
    label: TTbb_Hadronic
    color: '#332288'
  TTbb_SemiLep:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTbb_SemiLep.root
    label: TTbb_SemiLep
    color: '#88CCEE'
  TTTW:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTTW.root
    label: TTTW
    color: '#44AA99'
  TTTT:
    type: MC
    path: /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3
    files:
    - /Users/jhlee/ttHH/ntuple/skimmed/gen_tier3/TTTT.root
    label: TTTT
    color: '#117733'
