x509userproxy           = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/proxy.cert
getenv                  = True
executable              = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/run_JetHT_F.sh
arguments               = $(args)
output = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/JetHT_F_F_20250602-220256/job_JetHT_F.$(ClusterId).$(ProcId).out
MY.WantOS               = "el9"
MY.XRDCP_CREATE_DIR     = True
error = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/JetHT_F_F_20250602-220256/error_JetHT_F.$(ClusterId).$(ProcId).err
log = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/JetHT_F_F_20250602-220256/log_JetHT_F.$(ClusterId).log
request_memory          = 10 GB
+JobFlavour             = "tomorrow"
queue args from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/ResubmittedJobV3/JetHT_F_F_20250602-220256/arguments_failed_JetHT_F_F_20250602-220256.txt
