x509userproxy           = /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/proxy.cert
getenv                  = True
executable              = /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/run_one_hadd.sh
arguments               = $(args)
output                  = /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/_merge_workdir/AnalyzerOutput_btagtrig_20260729-224025/logs/job.$(ClusterId).$(ProcId).out
error                   = /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/_merge_workdir/AnalyzerOutput_btagtrig_20260729-224025/logs/job.$(ClusterId).$(ProcId).err
log                     = /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/_merge_workdir/AnalyzerOutput_btagtrig_20260729-224025/logs/log.$(ClusterId).log
MY.WantOS               = "el9"
request_memory          = 4GB
queue args from /u/user/jhlee/ttHH/CMSSW_14_2_1/src/tempTTHH/outputMerger/_merge_workdir/AnalyzerOutput_btagtrig_20260729-224025/arguments.txt
