x509userproxy           = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/proxy.cert
getenv                  = True
executable              = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/run_QCD_HT500to700.sh
arguments               = $(args)
output = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/QCD_HT500to700_HT500to700_20250602-220256/job_QCD_HT500to700.$(ClusterId).$(ProcId).out
MY.WantOS               = "el9"
MY.XRDCP_CREATE_DIR     = True
error = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/QCD_HT500to700_HT500to700_20250602-220256/error_QCD_HT500to700.$(ClusterId).$(ProcId).err
log = /eos/user/j/junghyun/ttHH/Btag_el9/ResubOutputV3/QCD_HT500to700_HT500to700_20250602-220256/log_QCD_HT500to700.$(ClusterId).log
request_memory          = 10 GB
+JobFlavour             = "tomorrow"
queue args from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/ResubmittedJobV3/QCD_HT500to700_HT500to700_20250602-220256/arguments_failed_QCD_HT500to700_HT500to700_20250602-220256.txt
