x509userproxy           = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/proxy.cert
getenv                  = True
executable              = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/run_ttWW.sh
arguments               = $(args)
output                  = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/tmp_ttWW_20250602-220256/job_ttWW.$(ClusterId).$(ProcId).out
MY.WantOS               = "el9"
MY.XRDCP_CREATE_DIR     = True
error                   = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/tmp_ttWW_20250602-220256/error_ttWW.$(ClusterId).$(ProcId).err
log                     = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/log_ttWW.$(ClusterId).log
request_memory          = 10 GB
+JobFlavour             = "tomorrow"
queue args from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_14_2_1/src/runii_tthhanalyzerV8/condor/filePath_Btag/arguments_ttWW.txt
